[options]

addons_path = odoo/addons,odoo/custom_addons,addons

admin_passwd = YOUR_ADMIN_PASSWORD

smtp_server = smtp.gmail.com
smtp_port = 587
smtp_user = YOUR_SMTP_USER
smtp_password = YOUR_SMTP_PASSWORD
smtp_tls = True
smtp_ssl = False
email_from = YOUR_SMTP_USER
