[options]

addons_path = odoo/addons,odoo/custom_addons,addons

db_host = localhost
db_port = 5432
db_user = odoo17user
db_password = odoo17pass

admin_passwd = Gaber@1907

wkhtmltopdf = C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe


# SMTP Gmail Configuration
smtp_server = smtp.gmail.com
smtp_port = 587
smtp_user = gaberfares66@gmail.com
smtp_password = rofg skzv jwrg bcjg
smtp_tls = True
smtp_ssl = False

email_from = gaberfares66@gmail.com