[options]

addons_path = odoo/addons,odoo/custom_addons,addons

db_host = ${PGHOST}
db_port = ${PGPORT}
db_user = ${PGUSER}
db_password = ${PGPASSWORD}
db_name = railway

admin_passwd = Gaber@1907

# SMTP Gmail Configuration
smtp_server = smtp.gmail.com
smtp_port = 587
smtp_user = gaberfares66@gmail.com
smtp_password = rofg skzv jwrg bcjg
smtp_tls = True
smtp_ssl = False

email_from = gaberfares66@gmail.com
